FROM envoyproxy/envoy-alpine-dev:latest

RUN apk update && apk add python3 bash curl
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./client.py /code
ADD ./start_client.sh /usr/local/bin/start_client.sh
RUN chmod u+x /usr/local/bin/start_client.sh
ENTRYPOINT /usr/local/bin/start_client.sh
